### PR TITLE
Feature/social media sharing

### PR DESCRIPTION
**Pull request by diskomotech**
Basic functionality for social media share buttons working. 

But we will need to grab the current page URL and use that in the href eventually. Leaving that for now because we only have localhost URLs at the moment.

### CODE REVIEW

**Comment by diskomotech** [comment]
Listings page is working for me now but it wasn't previously. Making the change in Routes to `component={ViewListingHolder}` was what I did to fix. I don't know if there's a better/alternative to fix? Also, I'm not sure why that page was the only one with the helmets problem

**Comment by dastrong** [comment]
> Listings page is working for me now but it wasn't previously. Making the change in Routes to `component={ViewListingHolder}` was what I did to fix. I don't know if there's a better/alternative to fix? Also, I'm not sure why that page was the only one with the helmets problem

Didn't we speak about that issue and I thought wrapping the component with a `withRouter` fixed it?

**Comment by diskomotech** [comment]
When I tried wrapping with withRouter it didn't seem to work but I wasn't sure if that was because I was implementing it wrongly or not. So I tried reverting back to the previous Routes code before the helmets were added and it was then loading the Listings page

**Comment by diskomotech** [comment]
OK. That seems to have fixed it! Should be good now to merge with my last commit

**Pull request merged**
